import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { SITE, MODES, PRICING } from './site.data.mjs';
import { DICTS, LANGS, layout } from './layout.mjs';
import { breadcrumbSchema } from './layout.mjs';
import {
  homePage,
  servicesPage,
  routesPage,
  calculatorPage,
  aboutPage,
  faqPage,
  contactsPage,
  privacyPage,
  termsPage,
  notFoundPage,
  faqSchema,
} from './pages.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const srcDir = path.join(root, 'src');

const PAGES = [
  { file: 'index.html', active: 'home', page: 'home', title: 'meta.home.title', desc: 'meta.home.desc', canonical: '', body: homePage },
  {
    file: 'services.html',
    active: 'services',
    page: 'services',
    title: 'meta.services.title',
    desc: 'meta.services.desc',
    canonical: 'services.html',
    body: servicesPage,
    crumbs: ['nav.services'],
    schemas: () => [
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        name: 'Закупка, проверка, консолидация и доставка грузов из Китая',
        serviceType: 'Международная логистика',
        provider: { '@type': 'Organization', name: SITE.brand, url: `${SITE.origin}/` },
        areaServed: ['RU', 'BY', 'KZ', 'KG'],
      },
    ],
  },
  {
    file: 'routes.html',
    active: 'routes',
    page: 'routes',
    title: 'meta.routes.title',
    desc: 'meta.routes.desc',
    canonical: 'routes.html',
    body: routesPage,
    crumbs: ['nav.routes'],
  },
  {
    file: 'calculator.html',
    active: 'calculator',
    page: 'calculator',
    title: 'meta.calculator.title',
    desc: 'meta.calculator.desc',
    canonical: 'calculator.html',
    body: calculatorPage,
    crumbs: ['nav.calculator'],
  },
  {
    file: 'about.html',
    active: 'about',
    page: 'about',
    title: 'meta.about.title',
    desc: 'meta.about.desc',
    canonical: 'about.html',
    body: aboutPage,
    crumbs: ['nav.about'],
  },
  {
    file: 'faq.html',
    active: 'faq',
    page: 'faq',
    title: 'meta.faq.title',
    desc: 'meta.faq.desc',
    canonical: 'faq.html',
    body: faqPage,
    crumbs: ['nav.faq'],
    schemas: () => [faqSchema()],
  },
  {
    file: 'contacts.html',
    active: 'contacts',
    page: 'contacts',
    title: 'meta.contacts.title',
    desc: 'meta.contacts.desc',
    canonical: 'contacts.html',
    body: contactsPage,
    crumbs: ['nav.contacts'],
    schemas: () => [
      {
        '@context': 'https://schema.org',
        '@type': 'ContactPage',
        name: 'Контакты LiHui Cargo',
        url: `${SITE.origin}/contacts.html`,
      },
    ],
  },
  {
    file: 'privacy.html',
    active: null,
    page: 'privacy',
    title: 'meta.privacy.title',
    desc: 'meta.privacy.desc',
    canonical: 'privacy.html',
    body: privacyPage,
    crumbs: ['footer.privacy'],
  },
  {
    file: 'terms.html',
    active: null,
    page: 'terms',
    title: 'meta.terms.title',
    desc: 'meta.terms.desc',
    canonical: 'terms.html',
    body: termsPage,
    crumbs: ['footer.terms'],
  },
  {
    file: '404.html',
    active: null,
    page: 'notfound',
    title: 'meta.404.title',
    desc: 'meta.404.desc',
    canonical: '404.html',
    body: notFoundPage,
    crumbs: [],
    noindex: true,
  },
];

/* ------------------------------------------------------------------ checks */

function assertDictionaryParity() {
  const base = Object.keys(DICTS.ru).sort();
  for (const lang of LANGS.filter((l) => l !== 'ru')) {
    const keys = Object.keys(DICTS[lang]).sort();
    const missing = base.filter((k) => !keys.includes(k));
    const extra = keys.filter((k) => !base.includes(k));
    if (missing.length) throw new Error(`[${lang}] missing keys: ${missing.join(', ')}`);
    if (extra.length) throw new Error(`[${lang}] unknown keys: ${extra.join(', ')}`);
  }
  return base.length;
}

/* ------------------------------------------------------------------ output */

function copyFile(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function writeI18nBundle() {
  const payload = {};
  for (const lang of LANGS) payload[lang] = DICTS[lang];
  const config = {
    site: {
      brand: SITE.brand,
      origin: SITE.origin,
      telegram: SITE.telegram,
      whatsapp: SITE.whatsapp,
      phone: SITE.phone,
    },
    modes: MODES,
    pricing: PRICING,
  };
  const js = [
    '/* Generated by tools/build.mjs — do not edit by hand. */',
    `window.LH_I18N = ${JSON.stringify(payload)};`,
    `window.LH_CONFIG = ${JSON.stringify(config)};`,
    '',
  ].join('\n');
  fs.writeFileSync(path.join(root, 'assets/js/i18n.js'), js, 'utf8');
  return js.length;
}

function writeSitemap(pages) {
  const urls = pages
    .filter((p) => !p.noindex)
    .map((p) => {
      const cleanPath = String(p.canonical || '').replace(/index\.html$/, '').replace(/\.html$/, '');
      const loc = `${SITE.origin}/${cleanPath}`;
      const priority = p.file === 'index.html' ? '1.0' : p.file === 'contacts.html' ? '0.9' : '0.7';
      return `  <url>
    <loc>${loc}</loc>
    <lastmod>${SITE.legalUpdated}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`;
    })
    .join('\n');
  fs.writeFileSync(
    path.join(root, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
    'utf8',
  );
}

function writeRobots() {
  fs.writeFileSync(
    path.join(root, 'robots.txt'),
    `User-agent: *\nAllow: /\n\nSitemap: ${SITE.origin}/sitemap.xml\n`,
    'utf8',
  );
}

function writeManifest() {
  const manifest = {
    name: SITE.brand,
    short_name: SITE.brandShort,
    description: 'Закупка, консолидация и доставка грузов из Китая в Россию и страны СНГ.',
    start_url: '/',
    display: 'browser',
    background_color: '#e9eff3',
    theme_color: '#071a2d',
    icons: [{ src: '/assets/brand/logo.png', sizes: 'any', type: 'image/png', purpose: 'any' }],
  };
  fs.writeFileSync(path.join(root, 'site.webmanifest'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
}

function main() {
  const keyCount = assertDictionaryParity();

  fs.mkdirSync(path.join(root, 'assets/css'), { recursive: true });
  fs.mkdirSync(path.join(root, 'assets/js'), { recursive: true });
  fs.mkdirSync(path.join(root, 'assets/brand'), { recursive: true });
  fs.mkdirSync(path.join(root, 'assets/img'), { recursive: true });

  copyFile(path.join(srcDir, 'assets/css/styles.css'), path.join(root, 'assets/css/styles.css'));
  copyFile(path.join(srcDir, 'assets/js/site.js'), path.join(root, 'assets/js/site.js'));
  for (const name of ['logo.png', 'favicon.svg']) {
    const from = path.join(srcDir, 'assets/brand', name);
    if (fs.existsSync(from)) copyFile(from, path.join(root, 'assets/brand', name));
  }

  // Raster assets (hero, portrait, QR codes) live in assets/img/ and are only
  // re-copied when a source copy exists, so a rebuild never deletes them.
  const rasterSrc = path.join(srcDir, 'assets/img');
  if (fs.existsSync(rasterSrc)) {
    for (const name of fs.readdirSync(rasterSrc)) {
      copyFile(path.join(rasterSrc, name), path.join(root, 'assets/img', name));
    }
  }
  for (const name of ['hero.jpg', 'ceo.jpg', 'qr-telegram.png', 'qr-whatsapp.png']) {
    if (!fs.existsSync(path.join(root, 'assets/img', name))) {
      console.warn(`  ! missing assets/img/${name} — the layout expects this file`);
    }
  }

  const bundleSize = writeI18nBundle();

  const written = [];
  for (const page of PAGES) {
    const schemas = [];
    if (page.crumbs && page.crumbs.length) {
      schemas.push(
        breadcrumbSchema(
          [{ name: 'Главная', path: '' }].concat(page.crumbs.map((key, index) => ({ name: DICTS.ru[key], path: page.canonical }))).slice(0, 2),
        ),
      );
    }
    if (page.schemas) schemas.push(...page.schemas());

    const html = layout({
      page: page.page,
      active: page.active,
      titleKey: page.title,
      descKey: page.desc,
      canonical: page.canonical,
      schemas,
      body: page.body(),
    });
    if (/undefined|NaN|\[object Object\]/.test(html)) {
      throw new Error(`Generated markup for ${page.file} contains an unresolved value`);
    }
    fs.writeFileSync(path.join(root, page.file), html, 'utf8');
    written.push({ file: page.file, bytes: Buffer.byteLength(html) });
  }

  writeSitemap(PAGES);
  writeRobots();
  writeManifest();

  const total = written.reduce((sum, p) => sum + p.bytes, 0);
  console.log(`i18n keys per language: ${keyCount}`);
  console.log(`i18n bundle: ${(bundleSize / 1024).toFixed(1)} KB`);
  for (const p of written) console.log(`  ${p.file.padEnd(18)} ${(p.bytes / 1024).toFixed(1)} KB`);
  console.log(`pages: ${written.length}, html total: ${(total / 1024).toFixed(1)} KB`);
}

main();
